services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - "MYSQL_DATABASE=scrumbags-db"
      - "MYSQL_PASSWORD=scrumbags"
      - "MYSQL_ROOT_PASSWORD=scrumbags"
      - "MYSQL_USER=scrumbags"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: team-scrumbags-server
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/scrumbags-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: scrumbags
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: ./client
    command: sh -c "npm start"
    ports:
      - "4200:80"
    working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - server

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - server

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  node_modules:
