apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: {{ .Values.global.namespace }}
data:
  init-db.sql: |
    CREATE DATABASE "pm-db";
    CREATE DATABASE "sdlc-db";
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: {{ .Values.global.namespace }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `comms-db`;
    CREATE DATABASE IF NOT EXISTS `transcription-db`;
    CREATE DATABASE IF NOT EXISTS `genai-db`;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: {{ .Values.global.namespace }}
data:
  trace-realm.json: |
    {
      "realm": "trace",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 30,
      "clients": [
        {
          "clientId": "trace-api",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "webOrigins": ["*"],
          "redirectUris": ["*"],
          "protocol": "openid-connect",
          "attributes": {
            "access.token.lifespan": "300",
            "access.token.lifespan.for.implicit.flow": "900"
          }
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "firstName": "Test",
          "lastName": "User",
          "email": "test@example.com",
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": false
            }
          ]
        },
        {
          "username": "testuser2",
          "enabled": true,
          "firstName": "Test",
          "lastName": "User2",
          "email": "test2@example.com",
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": false
            }
          ]
        }
      ]
    }