trace:
    sdlc:
        token-secret: ${TOKEN_SECRET}
        mode: ${MODE:forward}
    gen-ai:
        url: ${GENAI_URL}

spring:
    application:
        name: sdlc-connector

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_AUTH_URL}/realms/${KEYCLOAK_REALM}
