services:
  transcription-service:
    container_name: transcription-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "4269:4269"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - "MYSQL_URL=dbc:mysql://mysql:3306/${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "4270:3306"
    volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data: