services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_URL: dbc:mysql://mysql:3306/${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "4270:3306"
    volumes:
        - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  transcription-service:
    container_name: transcription-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      HF_TOKEN: ${HF_TOKEN}
      USE_CLOUD: ${USE_CLOUD}
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      TRANSCRIPTION_TIMEOUT: ${TRANSCRIPTION_TIMEOUT}
      GENAI_URL: ${GENAI_URL}

    ports:
      - "4269:4269"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data: