services:
  project-management:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - db
      - keycloak
    environment:
      - DEBUG=${DEBUG:-false}
      - DB_URL=jdbc:postgresql://localhost:5432/project-db
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-test}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-trace}
      - KEYCLOAK_AUTH_URL=http://localhost:8081
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - SERVER_PORT=8080
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command:
      - start-dev
      - --import-realm
      - --http-port=8081
    network_mode: host
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/

  db:
    image: postgres:latest
    network_mode: host
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test}
      POSTGRES_DB: project-db
      POSTGRES_PORT: 5432
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: