services:
  project-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG:-false}
      - DB_URL=jdbc:mysql://db:3306/project-db
      - DB_USER=user
      - DB_PASSWORD=test

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: project-db
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: