{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'discord'
    receivers:
      - name: 'discord'
        discord_configs:
          - webhook_url_file: /etc/alertmanager/secrets/discord_webhook_url
            send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image }}
          args:
            - '--config.file=/etc/alertmanager/config.yml'
            - '--storage.path=/alertmanager'
          ports:
            - containerPort: {{ .Values.alertmanager.port }}
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
            - name: alertmanager-storage
              mountPath: /alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
        - name: alertmanager-secret
          secret:
            secretName: trace-secrets
            items:
              - key: DISCORD_ALERTMANAGER_WEBHOOK_URL
                path: discord_webhook_url
        - name: alertmanager-storage
          persistentVolumeClaim:
            claimName: alertmanager-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - port: {{ .Values.alertmanager.port }}
      targetPort: {{ .Values.alertmanager.port }}
      nodePort: {{ .Values.alertmanager.nodePort }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanager.storageSize }}
{{- end }}