apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: {{ .Values.global.namespace }}
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS "project-db";
    CREATE DATABASE IF NOT EXISTS "sdlc-db";
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: {{ .Values.global.namespace }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `comms-db`;
    CREATE DATABASE IF NOT EXISTS `transcription-db`;
    CREATE DATABASE IF NOT EXISTS `genai-db`;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: {{ .Values.global.namespace }}
data:
  trace-realm.json: |
    {
      "realm": "trace",
      "enabled": true,
      "clients": [
        {
          "clientId": "trace-api",
          "enabled": true,
          "publicClient": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ]
    }