{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          command:
            - start-dev
            - --import-realm
          ports:
            - containerPort: {{ .Values.keycloak.port }}
          env:
            - name: KC_HOSTNAME
              value: localhost
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_PORT
              value: "{{ .Values.keycloak.port }}"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_PORT
              value: "{{ .Values.keycloak.port }}"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trace-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trace-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          volumeMounts:
            - name: keycloak-import
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: keycloak-import
          configMap:
            name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
      nodePort: 30999
{{- end }}