{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
          env:
            - name: KC_HOSTNAME_URL
              value: "https://{{ .Values.ingress.keycloakHost }}"
            - name: KC_PROXY
              value: "edge"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trace-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trace-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          volumeMounts:
            - name: keycloak-import
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: keycloak-import
          configMap:
            name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: 8080
      nodePort: {{ .Values.keycloak.port }}
      protocol: TCP
{{- end }}