apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.global.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ge58ler@mytum.de
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - http01:
          ingress:
            class: nginx