apiVersion: v1
kind: Secret
metadata:
  name: trace-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.environment.keycloakAdminUsername | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote | b64enc }}
  DB_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.postgresDbPassword | quote | b64enc }}
  POSTGRES_DB_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  POSTGRES_DB_PASSWORD: {{ .Values.secrets.postgresDbPassword | quote | b64enc }}
  POSTGRES_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresDbPassword | quote | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote | b64enc }}

  #Comms
  COMM_DB_USER: {{ .Values.environment.mysqlDbUser | quote | b64enc }}
  COMM_DB_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ "root" | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote | b64enc }}
  SDLC_TOKEN_SECRET: {{ .Values.environment.sdlcTokenSecret | quote | b64enc }}
  {{- if .Values.secrets.commDiscordSecret }}
  COMM_DISCORD_SECRET: {{ .Values.secrets.commDiscordSecret | quote | b64enc }}
  {{- end }}
  {{- if .Values.secrets.assemblyAiKey }}

  #Genai
  ASSEMBLYAI_API_KEY: {{ .Values.secrets.assemblyAiKey | quote | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hfToken }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote | b64enc }}
  {{- end }}
  {{- if .Values.secrets.nomicApiKey }}
  NOMIC_API_KEY: {{ .Values.secrets.nomicApiKey | quote | b64enc }}
  {{- end }}
  {{- if .Values.secrets.openWebuiBearer }}
  OPEN_WEBUI_BEARER: {{ .Values.secrets.openWebuiBearer | quote | b64enc }}
  {{- end }}

  # Monitoring
  {{- if .Values.secrets.grafanaAdminPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote | b64enc }}
  {{- end }}
  {{- if .Values.secrets.discordAlertmanagerWebhookUrl }}
  DISCORD_ALERTMANAGER_WEBHOOK_URL: {{ .Values.secrets.discordAlertmanagerWebhookUrl | quote | b64enc }}
  {{- end }}