apiVersion: v1
kind: Secret
metadata:
  name: trace-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.environment.keycloakAdminUsername | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.environment.keycloakAdminPassword | b64enc }}
  DB_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  DB_PASSWORD: {{ .Values.environment.postgresDbPassword | b64enc }}
  POSTGRES_DB_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  POSTGRES_DB_PASSWORD: {{ .Values.environment.postgresDbPassword | b64enc }}
  POSTGRES_USER: {{ .Values.environment.postgresDbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.environment.postgresDbPassword | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.environment.mysqlRootPassword | b64enc }}
  COMM_DB_USER: {{ "root" | b64enc }}
  COMM_DB_PASSWORD: {{ .Values.environment.mysqlRootPassword | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ "root" | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.environment.mysqlRootPassword | b64enc }}
  SDLC_TOKEN_SECRET: {{ .Values.environment.sdlcTokenSecret | b64enc }}