{{- if .Values.swagger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: {{ .Values.global.namespace }}
  labels:
    app: swagger-ui
    version: v1
spec:
  replicas: {{ .Values.swagger.replicas }}
  selector:
    matchLabels:
      app: swagger-ui
      version: v1
  template:
    metadata:
      labels:
        app: swagger-ui
        version: v1
    spec:
      containers:
      - name: swagger-ui
        image: {{ .Values.swagger.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: URLS
          value: '[{"url": "https://{{ .Values.ingress.host }}/api/project-management/v3/api-docs", "name": "Project Management API"}, {"url": "https://{{ .Values.ingress.host }}/api/sdlc/v3/api-docs", "name": "SDLC Connector API"}, {"url": "https://{{ .Values.ingress.host }}/api/communication/v3/api-docs", "name": "Communication API"}, {"url": "https://{{ .Values.ingress.host }}/api/meeting-notes/v3/api-docs", "name": "Transcription API"}, {"url": "https://{{ .Values.ingress.host }}/api/gen-ai/openapi.json", "name": "GenAI API"}]'
        - name: BASE_URL
          value: "/api/docs"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: swagger-ui
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.swagger.nodePort }}
    name: http
  selector:
    app: swagger-ui
{{- end }}
