{{- if .Values.weaviate.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.weaviate.storageSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.weaviate.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: {{ .Values.weaviate.image }}
          command:
            - /bin/weaviate
          args:
            - --host
            - 0.0.0.0
            - --port
            - "{{ .Values.weaviate.port }}"
            - --scheme
            - http
          ports:
            - name: http
              containerPort: {{ .Values.weaviate.port }}
            - name: grpc
              containerPort: 50051
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: ENABLE_API_BASED_MODULES
              value: "true"
            - name: CLUSTER_HOSTNAME
              value: "node1"
          volumeMounts:
            - name: weaviate-storage
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: {{ .Values.weaviate.port }}
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: {{ .Values.weaviate.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: weaviate-storage
          persistentVolumeClaim:
            claimName: weaviate-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: weaviate
  ports:
    - name: http
      port: {{ .Values.weaviate.port }}
      targetPort: {{ .Values.weaviate.port }}
    - name: grpc
      port: 50051
      targetPort: 50051
{{- end }}