services:
  sdlc-connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG:-true}
      - TOKEN_SECRET=${TOKEN_SECRET:-meinsecret}
      - SPRING_PROFILES_ACTIVE=${MODE:-persist}
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME:-sdlc-db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-test}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test}
      POSTGRES_DB: ${DB_NAME:-sdlc-db}
    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: