name: Deploy to Kubernetes (Rancher) with Helm

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy-helm:
    name: Kubernetes Deployment with Helm
    runs-on: ubuntu-latest
    environment: prod-vm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install -n team-scrumbags trace ./k8s  \
            --set secrets.postgresDbPassword="${{ secrets.POSTGRES_DB_PASSWORD }}" \
            --set secrets.mysqlRootPassword="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set secrets.assemblyAiKey="${{ secrets.ASSEMBLYAI_API_KEY }}" \
            --set secrets.commDiscordSecret="${{ secrets.COMM_DISCORD_SECRET }}" \
            --set secrets.hfToken="${{ secrets.HF_TOKEN }}" \
            --set secrets.nomicApiKey="${{ secrets.NOMIC_API_KEY }}" \
            --set secrets.openWebuiBearer="${{ secrets.OPEN_WEBUI_BEARER }}" \
            --set secrets.grafanaAdminPassword="${{ secrets.GRAFANA_ADMIN_PASSWORD }}" \
            --set secrets.discordAlertmanagerWebhookUrl="${{ secrets.DISCORD_ALERTMANAGER_WEBHOOK_URL }}" \