name: Deploy to Kubernetes (Rancher) with Helm

on:
  workflow_dispatch:

jobs:
  deploy-helm:
    name: Kubernetes Deployment with Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

#      - name: Set up Kubeconfig
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
#          chmod 600 ~/.kube/config

#      - name: Deploy with Helm
#        run: |
#          helm -n team-scrumbags upgrade trace ./k8s \
#            --set secrets.assemblyAiKey="${{ secrets.ASSEMBLYAI_API_KEY }}" \
#            --set secrets.projectDbUser="${{ secrets.PROJECT_DB_USER }}" \
#            --set secrets.projectDbPassword="${{ secrets.PROJECT_DB_PASSWORD }}" \
#            --set secrets.keycloakAdminUsername="${{ secrets.KEYCLOAK_ADMIN_USERNAME }}" \
#            --set secrets.keycloakAdminPassword="${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}" \
#            --set secrets.sdlcTokenSecret="${{ secrets.SDLC_TOKEN_SECRET }}" \
#            --set secrets.postgresDbUser="${{ secrets.POSTGRES_DB_USER }}" \
#            --set secrets.postgresDbPassword="${{ secrets.POSTGRES_DB_PASSWORD }}" \
#            --set secrets.mysqlRootPassword="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
#            --set secrets.commDiscordSecret="${{ secrets.COMM_DISCORD_SECRET }}" \
#            --set secrets.commDiscordBotId="${{ secrets.COMM_DISCORD_BOT_ID }}" \
#            --set secrets.hfToken="${{ secrets.HF_TOKEN }}" \
#            --set secrets.nomicApiKey="${{ secrets.NOMIC_API_KEY }}" \
#            --set secrets.openWebuiBearer="${{ secrets.OPEN_WEBUI_BEARER }}"