name: Check Dev Environment

on:
  push:
    branches:
      - dev-jeremy

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:27.5.1
        options: --privileged
    if: startsWith(github.event.head_commit.message, 'test:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run stack with Docker Compose
        run: docker compose up --build -d

      - name: Wait for Spring Boot to become healthy
        run: |
          timeout=60
          while [[ "$(docker inspect -f '{{.State.Health.Status}}' team-scrumbags-server)" != "healthy" ]]; do
            sleep 5
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "Spring Boot failed to start in time"
              docker logs team-scrumbags-server
              exit 1
            fi
          done
          echo "Spring Boot is healthy!"
