name: Genai build python
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "genai/**"
      - ".github/workflows/genai-build.yml"
  pull_request:
    paths:
      - "genai/**"
      - ".github/workflows/genai-build.yml"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./genai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        id: flake8
        run: |
          pip install flake8
          flake8 app --count --max-complexity=15 --max-line-length=127 --statistics

      - name: Run tests
        #env:
        #RABBITMQ_URL: amqp://guest:guest@localhost:5672/
        run: PYTHONPATH=. pytest
