name: Mock Meeting notes build
on: 
  push:
    branches:
      - main
      - release/*
    paths:
      - 'mock-meeting-notes/**'
      - '.github/workflows/mock-meeting-notes-package.yml'
  pull_request:
    paths:
      - 'mock-meeting-notes/**'
      - '.github/workflows/mock-meeting-notes-build.yml'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mock-meeting-notes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build -x test