name: Mock genai build
on: 
  pull_request:
    paths:
      - 'mock-genai/**'
      - '.github/workflows/mock-genai-build.yml'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mock-genai
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true
          cache-dependency-path: "./mock-genai/go.sum"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v -o mock-genai-app .