name: Project Management docker build and push
on:
  push:
    branches:
      - main
    paths:
      - 'project-management/**'
      - '.github/workflows/project-management-package.yml'
  release:
    types: [released]

jobs:
  build:
    uses: ./.github/workflows/project-management-build.yml

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/project-management
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./project-management
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}